AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
##########################################################################
#   S3 Buckets                                                           #
##########################################################################
  TestsBucket:
    Type: AWS::S3::Bucket
  ResultsBucket:
    Type: AWS::S3::Bucket
##########################################################################
#   SQS Queue                                                            #
##########################################################################
  TestJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 360
##########################################################################
#   ApiGateway                                                           #
##########################################################################
  ApiGatewayApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: 'Beta'
    Auth:
        ApiKeyRequired: true

##########################################################################
#   DynamoDB                                                            #
##########################################################################
  TestRunTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: run_id
        AttributeType: S
      - AttributeName: job_id
        AttributeType: S
      KeySchema:
      - AttributeName: run_id
        KeyType: HASH
      - AttributeName: job_id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  TestShardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: job_id
        AttributeType: S
      KeySchema:
      - AttributeName: job_id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST


##########################################################################
#   Lambda Function                                                      #
##########################################################################

  ExecutorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 1536
      EphemeralStorage:
        Size: 1024
      Timeout: 120
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TestJobQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          TestJobQueueName: !Ref TestJobQueue
          ResultsBucketName: !Ref ResultsBucket
          TestsBucketName: !Ref TestsBucket
          TestRunTableName: !Ref TestRunTable
          TestShardTableName: !Ref TestShardTable
          MergerFunctionName: !Ref MergerFunction
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref TestsBucket
        - S3FullAccessPolicy:
            BucketName: !Ref ResultsBucket
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TestJobQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref TestRunTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TestShardTable
        - LambdaInvokePolicy:
            FunctionName: !Ref MergerFunction
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./executor
      DockerTag: python3.9-v1
  DistributorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./distributor
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          TestJobQueueName: !Ref TestJobQueue
          ResultsBucketName: !Ref ResultsBucket
          TestsBucketName: !Ref TestsBucket
          TestRunTableName: !Ref TestRunTable
          TestShardTableName: !Ref TestShardTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              ApiKeyRequired: true
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref TestsBucket
        - S3FullAccessPolicy:
            BucketName: !Ref ResultsBucket
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TestJobQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref TestRunTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TestShardTable
    
  MergerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./merger
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          ResultsBucketName: !Ref ResultsBucket
          TestRunTableName: !Ref TestRunTable
          TestShardTableName: !Ref TestShardTable
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref TestsBucket
        - S3FullAccessPolicy:
            BucketName: !Ref ResultsBucket
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TestJobQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref TestRunTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TestShardTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              ApiKeyRequired: true

Outputs:
  DistributorFunction:
    Description: Distributor Function ARN
    Value: !Ref DistributorFunction

  MergerFunction:
    Description: Merger Function ARN
    Value: !Ref MergerFunction

  ExecutorFunction:
    Description: Executor Function ARN
    Value: !Ref ExecutorFunction
  
  TestJobQueueName:
    Description: SQS queue name
    Value: !GetAtt TestJobQueue.QueueName

  TestJobQueueARN:
    Description: SQS queue ARN
    Value: !GetAtt TestJobQueue.Arn

  TestJobQueueURL:
    Description: SQS queue URL
    Value: !Ref TestJobQueue

  TestsBucketName:
    Description: Tests bucket name
    Value: !Ref TestsBucket

  ResultsBucketName:
    Description: Results bucket name
    Value: !Ref ResultsBucket